'use strict';

// cast — the help pages: `cast -h` and `cast <verb> -h`.

const { API_USAGE } = require('./api');
const { RESUME_USAGE, SESSIONS_USAGE, USAGE_IG } = require('./core');
const { USAGE: MODELS_USAGE } = require('./models');
const { loadOptional } = require('./optional');
const path = require('path');
const { ROUTE_FORMS, ROUTE_USAGE } = require('./route');

const { module: monitorMod } = loadOptional('monitor');
const MONITOR_USAGE = monitorMod
  ? monitorMod.MONITOR_USAGE
  : 'cast monitor — unavailable: lib/monitor.js failed to load (run `cast monitor` for the error)';

// The two pages of the rbtv repository the help sends a reader to: the path from the repository
// root, and the absolute path in the copy of rbtv this cast runs from.
function sourcePage(rel) {
  return { rel, abs: path.resolve(__dirname, '..', '..', '..', '..', '..', '..', rel) };
}
const FRAMEWORK_SKILL = sourcePage('core/rbtv/skills/framework.md');
const MODEL_CATALOG_PAGE = sourcePage('core/cast/capabilities/tools/cast/documentation/personalizing-the-model-catalog.md');


function printHelp() {
  const lines = [
    'cast — launch one headless agent turn. Prints the child\'s stdout/stderr and exits',
    'with its exit code. --headed opens the harness\'s interactive TUI instead (the task',
    'becomes the first message).',
    '',
    'Usage:',
    `  ${USAGE_IG}`,
    '      an rbtv agent: its folder holds the prompt and the harness, model and effort.',
    '  cast <harness> <model> <effort 1-5> [launch-folder] (-p TEXT | -f FILE)',
    '      [-s TEXT | -S FILE | --rogue PROMPT-FILE] [--headed] [--dry-run]',
    '      for a worker chosen by `cast route`, or a throwaway.',
    '',
    '  cast resume <harness> <session-id|last> [launch-folder]',
    '      (-p TEXT | -f FILE) [--dry-run]',
    `  ${SESSIONS_USAGE}`,
    '  cast monitor [--watch] [--stall SECONDS] [--grace SECONDS]',
    '      [--poll SECONDS] [--deadline SECONDS] [--folder PREFIX] [--json]',
    '  cast route --access open|bounded --type code|text',
    '      --class planner|broad|bounded|mechanical',
    '      [--optimize price|quality] [--caps image] [--explain]',
    '  cast route --batch agents.json',
    '  cast list [--agents [--full] | --agent NAME] [--target FOLDER] [--json]',
    '  cast models list | add HARNESS MODEL | remove HARNESS MODEL',
    '  cast api <model> ...   |   cast doctor [--json]   |   cast -h',
    '',
    '-p TEXT / -f FILE  the TASK: what this one launch must do. -f - reads standard input.',
    '                   With --agent, omitting both sends the agent folder\'s task.md.',
    '--agent AGENT      a name under <installation>/.rbtv/agents/, or the path of an agent',
    '                   folder. Do not pass harness, model or effort; to change them:',
    '                   rbtv agent configure AGENT. Sets RBTV_AGENT_HOME.',
    '<effort 1-5>       N picks the Nth rung, clamped to the model\'s top — pass the number,',
    '                   the words are labels only.',
    '[launch-folder]    defaults to the current directory.',
    'Harnesses, models, and what each effort number means on each model:',
    '  cast models list',
    '',
    'Writing an agent to launch? Make it an rbtv agent: a folder, anywhere, that holds',
    'prompt.md (its prompt) and agent.json (its record). First load the framework skill',
    `and follow it: ${FRAMEWORK_SKILL.rel} in the rbtv repository;`,
    'the same file on this machine:',
    `  ${FRAMEWORK_SKILL.abs}`,
    'Then, with H, M and E chosen by `cast route` or picked from `cast models list`:',
    '  rbtv agent add FOLDER --harness H --model M --effort E',
    '  cast --agent FOLDER -p "..."',
    '',
    'Without an rbtv agent — for a launch that will not be repeated:',
    '  -s TEXT / -S FILE  system prompt: real for claude, developer instructions for codex,',
    '                     prepended to the first message for opencode.',
    '  --rogue PROMPT-FILE  rogue agent: the body of PROMPT-FILE is the system prompt.',
    '                     For a prompt you will not keep.',
    '',
    'cast list      the rbtv agents cast --agent can launch from here; --target FOLDER:',
    '               those of FOLDER',
    'cast models    the models this installation selected for launching: list, add, remove',
    'cast doctor    harness programs found; logins present for the selected models',
    'cast resume    one more turn into a session id, or `last` for the folder newest',
    'cast sessions  what ran in a folder — harness, id, started, first-message label',
    'cast route     answer 4 questions about the job, get (harness, model, mode, effort)',
    'cast monitor   live cast jobs; --watch exits 3 on stall, 4 on ENDED.',
    '',
    'Example: cast --agent scout -p "reply with exactly: ok"',
    '         cast --agent plans/launch/agents/drafter   # sends its task.md',
    '         cast claude sonnet-5-5 3 -p "reply with exactly: ok"',
    '',
    'next: cast <verb> -h   # every flag of one verb, with examples',
    'Exit codes: the child\'s code on a launch; 2 refused or invalid arguments.',
  ];
  process.stdout.write(lines.join('\n') + '\n');
}


// --- per-verb help: `cast <verb> -h` -----------------------------------------------------------
//
// The top-level -h is the shape of a launch and where an agent is made; these pages are the flags. Each
// one states what the verb DOES, what every flag means, and one example that runs as pasted.
// ponytail: plain string map, no help framework. Keep each page under a screen.

function verbHelpPages() {
  return {
    resume: [
      `usage: ${RESUME_USAGE}`,
      '',
      'Send one more turn into a session that already ran. The session keeps its history and its',
      'system prompt; you only supply the new message. Headless only.',
      '',
      '  <harness>          claude | codex | opencode — the one that ran it.',
      '  <session-id|last>  id from `cast sessions`, or the literal `last` for that folder\'s newest.',
      '  [launch-folder]    the folder the session ran in. Default: current directory.',
      '  -p TEXT | -f FILE  the message for this turn (required).',
      '  --dry-run          print the argv/cwd it would spawn as JSON, launch nothing.',
      '',
      '  --headed and -s/-S are refused: the session is already open and already has its prompt.',
      '',
      'example: cast resume claude last -p "now say it in Portuguese"',
    ],
    sessions: [
      `usage: ${SESSIONS_USAGE}`,
      '',
      'What ran in a folder — one line per session, newest first, across all three harnesses or',
      'just one. The ids printed here are what `cast resume` takes.',
      '',
      '  [harness]        claude | codex | opencode. Omitted = all three, merged.',
      '  [launch-folder]  which folder\'s sessions. Default: current directory.',
      '  -n N             keep at most N per harness (default 10), so one busy harness cannot',
      '                   crowd the others out of the merged view.',
      '  --json           machine-readable rows: harness, id, started (ISO), label.',
      '',
      'columns: harness, session id, started, first-message label.',
      '',
      'example: cast sessions claude .rbtv/agents/writer -n 3',
    ],
    monitor: [
      `usage: ${MONITOR_USAGE}`,
      '',
      'The freeze tripwire. Reports jobs that are ALIVE BUT FROZEN, and on --watch a job',
      'that left the roster (ENDED). Killing a stall is the caller\'s call. Two channels:',
      'harness progress, and a witness of life from the process tree + stdout capture.',
      'A freeze verdict needs BOTH silent. States:',
      '  STALLED         no harness progress for --stall seconds AND the tree shows no life.',
      '  NO-SIGNAL       no signal AND no work of any kind ever, --grace seconds past launch.',
      '  SUSPECT         harness silent but the tree is alive — never an event; verify first.',
      '  provider-limit  usage-limit / 429 / insufficient-balance in stdout or harness log.',
      '  DEADLINE        wall-clock --deadline exceeded, independent of activity.',
      '  ENDED           --watch: a seen-alive job is gone. Once, then suppressed.',
      '             ENDED <pid> <harness> <folder> alive=<N>s last-state=<state>',
      '',
      '  (no flags)         one-shot roster: FOLDER HARNESS MODEL PID ELAPSED PROGRESS STATE.',
      '  --watch            silent while healthy. Freeze → exit 3. Only ENDED → exit 4.',
      '                     Both in one poll → 3. Armed empty → 0. 4 is never 3: 3 is',
      '                     kill-or-verify authority; the departed process is already gone.',
      '                     Every event burst trails an ADVISORY line: this monitor is never',
      '                     authority to kill — verify life yourself first (owner, 2026-08-22).',
      '  --stall SECONDS    freeze threshold, default 600. Measured 0 false positives at 600',
      '                     across 12,371 healthy gaps / 94 runs — do not lower it. Nothing',
      '                     advances during a single long tool call.',
      '  --grace SECONDS    how long a fresh job may show no signal at all, default 60.',
      '  --poll SECONDS     --watch sleep between sweeps, default 30.',
      '  --deadline SECONDS wall-clock cap per job, default 14400 (4h). Independent of',
      '                     activity. Launch spawnSync uses the same cap (CAST_DEADLINE_MS).',
      '                     Monitor never kills — DEADLINE is advisory, like STALL.',
      '  --folder PREFIX    only jobs whose folder starts with PREFIX.',
      '  --json             roster as JSON. Refused with --watch (that form prints events).',
      '',
      'An empty roster means "no REGISTERED launch is live" — jobs started outside cast, or',
      'before the registry existed, are invisible here. It is not proof the box is quiet.',
      '',
      'example: cast monitor --watch --folder 1-projects/my-project/build/plan',
    ],
    route: [
      `usage: ${ROUTE_USAGE}`,
      ...ROUTE_FORMS.map((f) => `       ${f}`),
      '',
      'Route answers ONE question: which worker runs this job. You answer four about the job.',
      'Deterministic — no network, no clock, no randomness: the same answers against the same',
      'model catalog always give the same verdict. One JSON verdict on stdout, exit 1 on error.',
      'Three flags are REQUIRED (--access, --type, --class). There are no silent defaults: an',
      'unanswered question is a guess, and a guess is what this command exists to remove. The',
      'one RULED default is --optimize (owner 2026-08-22): omit it and you get PRICE, for',
      'every class alike. The class\'s levels are all that stands between a job and the',
      'cheapest model in the model catalog.',
      '',
      'THE INTERVIEW',
      '',
      '  --access open | bounded',
      '    Q: must the agent navigate and DISCOVER files on disk?',
      '       open     yes — it will roam a repo it was not handed. API workers are dropped:',
      '                an API worker has no disk.',
      '       bounded  no — known files only, or no disk at all. API workers stay in play.',
      '',
      '  --type code | text',
      '    Q: is the work code, or is it prose/analysis?',
      '       code     ranks on the coding score.',
      '       text     ranks on the reasoning score. PLANNING IS TEXT, even for a coding job —',
      '                deciding what to build is not writing it.',
      '',
      '  --class planner | broad | bounded | mechanical',
      '    Q: how bounded is the work? This picks BOTH the ONE quality tier in play and the effort.',
      '       planner     unbounded judgement, decides what others do.  tier  SOTA      effort 3*',
      '       broad       wide but the goal is clear.                   tier  L1        effort 2/3',
      '       bounded     a defined change with a known shape.          tier  L2        effort 2',
      '       mechanical  one obviously-correct edit, no judgement.     tier  L3        effort 1',
      '    (effort shown as code/text where they differ. * planner\'s 3 is a FLOOR — the verdict',
      '     says effort_is_floor:true and YOU raise it for criticality, complexity or blast',
      '     radius. Route does not decide that.)',
      '    A class sees exactly one tier (owner ruling 2026-09-24): --optimize only reorders',
      '    that tier, so a bounded job never reaches an L1 model, and only planner reaches SOTA.',
      '',
      '  --optimize price | quality   (optional — omitted means price)',
      '    Q: cheapest worker that qualifies, or best worker that qualifies?',
      '       price    lowest $/M output tokens. Ties: higher score, then alphabetical.',
      '                A row with a blank cost sits OUT of price picks — unknown is not cheap.',
      '       quality  highest score in the class\'s tier. Ties: lower cost, then alphabetical.',
      '       (omitted) PRICE — identical to passing --optimize price, for every class (owner',
      '                ruling 2026-08-22, replacing the two-band rule of the day before).',
      '                Only --optimize quality ranks on score at all.',
      '',
      '  --caps image   (optional)',
      '    Q: does the job need a specific capability?',
      '       image  SHORT-CIRCUITS everything: you get the image-generation row and none of the',
      '              other questions are asked. `cast route --caps image` on its own is valid.',
      '',
      'VERDICT',
      '  {"verdict":"route","harness":"claude","model":"opus-5-5","mode":"cli","effort":3,',
      '   "effort_is_floor":true,"alternates":[{"harness":...},{...}]}',
      '  mode is cli (launch it with `cast <harness> <model> <effort>`) or api (`cast api`).',
      '  The top-level worker IS the choice — launch it. `alternates` is the next two of the same',
      '  ranking, as backups for when the first cannot be launched; they share the same effort.',
      '  Fewer than two alternates (or none) just means the ranking was that short.',
      '  For an agent launched more than once, put the verdict in its record instead of typing it',
      '  at each launch: `rbtv agent add FOLDER --harness H --model M --effort E` for a new agent,',
      '  `rbtv agent configure AGENT --harness H --model M --effort E` for an existing one.',
      '  errors: {"error":"malformed_request"|"zero_candidates"|"no_models","details":...}',
      '',
      'BATCH — a whole team in one call',
      '  cast route --batch agents.json   (or --batch - to read the JSON from stdin)',
      '  Planning mode designs every agent at once; batch turns that into ONE deterministic',
      '  assignment table instead of N shell calls. Input is a JSON array of agent objects (or',
      '  {"agents":[...]}), each one the interview as an object with a unique name:',
      '    {"name":"planner","access":"open","type":"text","class":"planner",',
      '     "optimize":"quality"}',
      '  Same vocabulary and required-ness as the flags (optimize optional, same price default;',
      '  caps:["image"] short-circuits the same',
      '  way — and an unknown key on an agent is a refusal, never a silent ignore. Output, one',
      '  entry per agent in INPUT order, the name mapping each verdict back to its agent:',
      '    {"verdict":"route-batch","agents":[',
      '      {"name":"planner","verdict":"route","harness":...,"alternates":[...]},',
      '      {"name":"fixer","error":"zero_candidates","details":"..."}]}',
      '  Exit 0 only when EVERY agent routed; 1 when any agent errored. A per-agent error never',
      '  aborts the batch — every agent\'s problem is reported in its own entry, so the whole',
      '  plan is fixed in one pass. A bad envelope (unreadable file, invalid JSON, empty stdin,',
      '  empty or duplicate-named agent list) refuses the whole call with one',
      '  {"error":"malformed_request","details":[...]} object and routes nothing.',
      '  --explain attaches each agent\'s own trace to that agent\'s entry. --batch combines with',
      '  none of the interview flags, nor with --caps.',
      '',
      'THE MODEL CATALOG',
      '  Route ranks the rows of the installation\'s model catalog, the table',
      '  `cast models list --catalog` prints. What its columns and `use` values mean, and how to',
      '  change them, is in the rbtv repository:',
      `  ${MODEL_CATALOG_PAGE.rel}`,
      `  ${MODEL_CATALOG_PAGE.abs}`,
      '',
      'flags',
      '  --explain   attach the full trace: every row that dropped, at which stage, and why.',
      '',
      'examples',
      '  cast route --access bounded --type code --class mechanical            # default = price',
      '  cast route --access bounded --type code --class mechanical --optimize price',
      '  cast route --access open --type text --class planner --optimize quality --explain',
      '  cast route --access bounded --type text --class broad --optimize price',
      '  cast route --caps image',
      '  cast route --batch agents.json --explain',
    ],
    api: [
      `usage: ${API_USAGE}`,
      '',
      'Run one API worker (no CLI harness involved) and write its output to disk. GOOGLE ONLY:',
      'the Gemini chat worker and the Google image-generation worker. `cast models list`',
      'shows which models have mode=api. A model the installation has not selected is refused.',
      '',
      '  <model>                which api model to call (see `cast models list`).',
      '  <effort 1-5>           mapped onto that model\'s own reasoning ladder. 1 = thinking off.',
      '  -p TEXT                the task, typed inline. Saved to <output-folder>/task.md.',
      '  -f FILE                the task, read from a file. Mutually exclusive with -p.',
      '  --output-folder DIR    where the response and run artifacts are written. Required.',
      '  --image                image generation: the task in, image FILES out into the output',
      '                         folder. No JSON envelope is asked for and none is parsed.',
      '  --input-image PATH     send an EXISTING image file IN alongside the task — "edit this',
      '                         picture", "restyle this logo", "use this as reference". Repeatable',
      '                         (order is preserved). Requires --image; refused without it. Bad',
      '                         path or an extension outside png/jpg/jpeg/webp/gif is refused.',
      '  --target-file PATH     append this file\'s contents to the task.',
      '  --timeout N            seconds to wait before giving up.',
      '  --grounded             enable Google web-grounding. Refused together with --image.',
      '  --extra-params JSON    raw provider parameters merged into the request body.',
      '  --dry-run              print the request it would send, call nothing, write nothing.',
      '',
      'example: cast api gemini-3.5-flash 3 -p "summarise this" --output-folder out/',
      '         cast api gemini-3.1-flash-image 1 --image -p "a red bicycle" --output-folder out/',
      '         cast api gemini-3.1-flash-image 1 --image --input-image logo.png \\',
      '           -p "restyle this logo in art deco" --output-folder out/',
    ],
    doctor: [
      'usage: cast doctor [--json]',
      '',
      'What can this machine launch? Two checks, read from local files and the environment only:',
      'no network call is made and no other program is started. Nothing is changed.',
      '',
      '  harnesses         claude, codex and opencode: the path PATH finds each at, or MISSING.',
      '  logins            for each selected model, whether the login of its provider is present.',
      '                    claude and codex: the login files the harness keeps in the home folder.',
      '                    Every other provider: its key variable in the OS environment or in the',
      '                    installation\'s environment file (.rbtv/config/env/.env), or its entry in',
      '                    opencode\'s credential store. A login is shown with where it was found,',
      '                    a missing one with what was looked for; no key, token or account name is',
      '                    ever printed.',
      '',
      'The selected models are the ones `cast models list` shows: the supported models the',
      'installation\'s model catalog (.rbtv/config/cast/models.csv) holds a row for, or every',
      'supported model while it has no such file. The installation is the first folder, from the',
      'current one upward, that holds .rbtv/config/install.json; outside one, every supported',
      'model is checked and no environment file is read. Which login each provider needs is data',
      'in providers.json, beside cast.js.',
      '',
      'cast doctor takes no name and no other option: it always checks everything. A present',
      'login is not proof that the account still has credit; accounts, saved logins and plan',
      'usage are `rbtv providers list` and `rbtv providers usage`, which the report ends with.',
      '',
      '  --json  one JSON object instead of the text report:',
      '          {installation, selection, catalog_problem, harnesses: {name: path},',
      '           models: [{harness, model, provider, login, via, reason}], next: [command, ...]}',
      '          installation and a harness path are null when not found. selection is the',
      '          installation\'s model catalog, null while the shipped one is in force.',
      '          catalog_problem is null, or why that file could not be read: then models is',
      '          empty. via says where a login was found and is null without one; reason says',
      '          what is missing and is null when login is true.',
      '',
      'Exit 0 whenever the report is printed, whatever it found. A word it does not take is',
      'refused: text on standard error, exit 2, with or without --json.',
      '',
      'examples: cast doctor',
      '          cast doctor --json',
    ],
    models: [
      `usage: ${MODELS_USAGE[0]}`,
      ...MODELS_USAGE.slice(1).map((form) => `       ${form}`),
      '',
      'The models of one installation: the one that holds the current folder, which is the first',
      'folder upward with .rbtv/config/install.json. A model can be launched there when cast',
      'supports it AND the installation selected it. The selected models are the rows of the',
      'installation\'s model catalog, .rbtv/config/cast/models.csv; while an installation has no',
      'such file, and outside any installation, every supported model is selected. Every result',
      'names the installation and the file it read or changed.',
      '',
      'cast models list — only reads.',
      '  --selected   the default: the models that can be launched here, each with what every',
      '               effort number 1-5 means on it.',
      '  --supported  every model this copy of cast can launch, with selected yes or no.',
      '  --catalog    every row of the model catalog in force, with the routing columns cast route',
      '               reads, whether cast supports the row (launchable) and whether its login is',
      '               present (available). A row cast does not support is shown, never hidden.',
      '  --json       --selected and --supported: {installation, selection, view, models:',
      '               [{harness, model, mode, rungs, effort_numbers, selected}], usage}.',
      '               selection is the installation\'s file, null while the shipped one is in',
      '               force. mode is cli or api. rungs are the model\'s own effort words, lowest',
      '               first; effort_numbers maps each word to the number that selects it.',
      '               --catalog: {installation, source, rows: [the 12 columns, launchable,',
      '               available]}. source is the file that was read.',
      '',
      'cast models add HARNESS MODEL — select a supported model.',
      '  HARNESS MODEL  as in a launch: claude haiku-4-5. An api model takes harness api.',
      '  It adds the model\'s row from the model catalog shipped with cast (a model listed at two',
      '  levels has two rows) to the installation\'s file and prints each row with what its use',
      '  value means. No login is checked: cast doctor does that. Already selected, or an',
      '  installation with no file of its own, changes nothing and exits 0.',
      '',
      'cast models remove HARNESS MODEL — stop launching a model here.',
      '  It deletes the model\'s rows from the installation\'s file. An installation with no file',
      '  of its own first gets a copy of the shipped one, so every other model stays selected. A',
      '  row cast no longer supports can be removed too. Not selected changes nothing, exit 0.',
      '  Refused while something in the installation still launches the model: an agent under',
      '  .rbtv/agents/ whose agent.json names it, or the Dreamer when it is on',
      '  (.rbtv/config/ignite/config.json, dreamer.model). The refusal lists them.',
      '  --force      remove it anyway; the result lists who still names it.',
      '  The result also says what was not checked: agents kept outside .rbtv/agents/, and',
      '  settings of a component that name a model.',
      '',
      '  --dry-run    add, remove: print what would change and write nothing.',
      '  --json       add: {installation, selection, harness, model, changed, added: [row],',
      '               dry_run}. remove: {installation, selection, harness, model, changed,',
      '               removed: [row], copied_shipped, users: [{kind, name, file}], not_checked:',
      '               [text], dry_run}. kind is agent or dreamer.',
      '',
      'The file is replaced in one step and keeps its own line ending. It is committed with the',
      'installation, so every machine and the Ignite daemon share one choice; a change counts from',
      'the next launch.',
      '',
      'Exit 0 for a result, a change or no change. A refusal exits 2: text on standard error, or',
      'with --json one value on standard output, {error, message, next}. No refusal changes',
      'anything.',
      '',
      'Changing the routing columns of a row, or the models cast supports:',
      `  ${MODEL_CATALOG_PAGE.rel} in the rbtv repository`,
      `  ${MODEL_CATALOG_PAGE.abs}`,
      '',
      'examples: cast models list',
      '          cast models list --supported --json',
      '          cast models add claude haiku-4-5',
      '          cast models remove opencode k3-256k --dry-run',
    ],
    list: [
      'usage: cast list [--agents [--full] | --agent NAME] [--target FOLDER] [--json]',
      '',
      'The rbtv agents. It only reads: nothing is launched or changed. The models are',
      '`cast models list`.',
      '',
      '--agents, or no flag: the rbtv agents `cast --agent NAME` can launch from here, which are',
      'the agents in the nearest .rbtv/agents/ folder above the current directory. Columns: name,',
      'harness, model, effort, Ignite (yes when the agent\'s ignite pack is on, which `ignite',
      'connect` does; such an agent also wakes from Slack), and description. The description is',
      'shortened to fit the line; with --full, or on a narrow terminal, each agent is a labeled',
      'block with its whole description. An agent that cannot be launched is named with the',
      'reason: an unreadable record, or a model the installation has not selected, with the',
      'command that selects it. No agent found is success.',
      '',
      '--agent NAME: that one agent in full: its folder, its whole description, and what is',
      'installed in it, under the names `rbtv show` takes: each pack on its own row, with the',
      'skills, rules, commands, MCP servers and hooks it installs on a row each under it; then, by',
      'kind, what is installed outside a pack. The view ends with the two commands that tell more',
      'about a name, ready to copy: `rbtv show NAME` (a pack: `rbtv show --pack NAME`) with',
      '`--target` and the agent\'s folder, so that rbtv answers for this agent. NAME is a name or',
      'a path, as for `cast --agent NAME`. What is installed is asked of the installer',
      '(`rbtv list --installed`); without rbtv on PATH the view says so and shows the rest.',
      '',
      '--target FOLDER: list the agents of FOLDER instead of those above the current directory.',
      'FOLDER is an installation (it holds .rbtv/): the agents in its .rbtv/agents/. Or an agent',
      'folder: that one agent. Or a folder that holds agent folders, such as the agents/ folder of',
      'a plan: those agents. A FOLDER that is none of the three is refused. With --agent NAME, NAME',
      'is a name among those agents, never a path. An agent outside .rbtv/agents/ is launched by',
      'its path: cast --agent FOLDER/NAME.',
      '',
      '  --full  with --agents: every description whole. One agent is always shown in full.',
      '  --json  with --agents: {folder, agents: [{name, description, harness, model, effort, ignite,',
      '            home}]}. folder is the folder the agents were read from, null when no',
      '            .rbtv/agents/ folder was found. An agent that cannot be launched is',
      '            {name, home, problem} instead.',
      '          with --agent NAME: that agent\'s object, plus installed: {pack, skill, rule,',
      '            command, mcp-server, hook}. pack is a list of {name, skill, rule, command,',
      '            mcp-server, hook}: each pack with the names it installs. The other five are',
      '            lists of the names installed outside a pack. installed is null, with the',
      '            reason in installed_problem, when the installer could not be asked.',
      '',
      'A refusal is text on standard error, exit 2, with or without --json.',
      '',
      'examples: cast list',
      '          cast list --agents --target plans/launch/agents',
      '          cast list --agents --json',
      '          cast list --agent scout',
    ],
  };
}

module.exports = {
  printHelp, verbHelpPages,
};
