'use strict';

// cast — per-verb help pages: `cast <verb> -h`.
// Split out of cast.js 2026-08-20 on the file's own section banners; the code below is
// unchanged from that file. Every composed argv and every stdout surface stayed
// byte-identical across the split (163-invocation corpus, both self-check suites).

const { API_USAGE } = require('./api');
const { RESUME_USAGE, SEAT_USAGE, SESSIONS_USAGE, USAGE, modelTable } = require('./core');
const { loadOptional } = require('./optional');
const { ROUTE_FORMS, ROUTE_USAGE } = require('./route');

const { module: monitorMod } = loadOptional('monitor');
const MONITOR_USAGE = monitorMod
  ? monitorMod.MONITOR_USAGE
  : 'cast monitor — unavailable: lib/monitor.js failed to load (run `cast monitor` for the error)';


function printHelp() {
  const lines = [
    "cast — launch one headless sub-agent turn in a chosen harness/model/effort.",
    "Prints the child's stdout/stderr and exits with its exit code.",
    "--headed launches the harness's interactive TUI instead (prompt becomes the first message).",
    '',
    `Usage: cast ${USAGE.slice('cast '.length)}`,
    `       ${SEAT_USAGE}`,
    `       ${RESUME_USAGE}`,
    `       ${SESSIONS_USAGE}`,
    `       ${MONITOR_USAGE}`,
    `       ${ROUTE_USAGE}`,
    // The batch form is the one route surface a caller cannot guess from the interview line;
    // taken from ROUTE_FORMS so this line can never drift from the route help page.
    ...ROUTE_FORMS.filter((f) => f.includes('--batch')).map((f) => `       ${f}`),
    '       cast api <model> …   |   cast doctor [--json]   |   cast list [--json]   |   cast -h',
    '',
    'Models (harness, model, what each effort number means):',
    ...modelTable(),
    '',
    "effort N picks the Nth rung, clamped to the model's top.",
    '[launch-folder] defaults to the current directory.',
    '-s TEXT / -S FILE: system prompt — real for claude, prepended to the first message elsewhere.',
    '',
    'cast seat      launch per seat.md frontmatter (harness/model/effort); seat.md is the',
    '               system prompt, -p/-f an optional wake message on top',
    'cast resume    one more turn into an existing session: id from `cast sessions`, or',
    "               `last` for the folder's newest",
    'cast sessions  what ran in a folder — harness, id, started, first-prompt label',
    'cast route     answer 4 questions about the job, get (harness, model, mode, effort)',
    'cast monitor   roster of live cast jobs; --watch is a freeze tripwire — silent while healthy,',
    '               exits 3 on stall, 4 on ENDED. A departure is not a freeze.',
    '',
    'Example: cast claude sonnet-5 3 -p "reply with exactly: ok"',
    '         cast resume claude last -p "now say it in Portuguese"',
    '',
    'next: cast <verb> -h   # every flag of one verb, with examples',
  ];
  process.stdout.write(lines.join('\n') + '\n');
}


// --- per-verb help: `cast <verb> -h` -----------------------------------------------------------
//
// The top-level -h is the model table and the shape of a launch; these pages are the flags. Each
// one states what the verb DOES, what every flag means, and one example that runs as pasted.
// ponytail: plain string map, no help framework. Keep each page under a screen.

function verbHelpPages() {
  return {
    seat: [
      `usage: ${SEAT_USAGE}`,
      '',
      'Launch a seat: the folder\'s seat.md IS the run. Its frontmatter picks harness/model/effort',
      'and its body becomes the system prompt, so nothing about the model is typed on the command',
      'line. -p/-f is an optional wake message layered on top of the descriptor.',
      '',
      '  [launch-folder]  where seat.md lives and where the agent runs. Default: current directory.',
      '  -p TEXT          wake message. Omitted -> "act per your seat descriptor."',
      '  -f FILE          same, read from a file.',
      '  --headed         open the harness TUI instead of running headless.',
      '  --dry-run        print the argv/cwd it would spawn as JSON, launch nothing.',
      '',
      '  -s/-S is refused here: the system prompt is seat.md.',
      '',
      'example: cast seat .rbtv/goals/my-goal/seats/writer -p "second pass, ship it"',
    ],
    resume: [
      `usage: ${RESUME_USAGE}`,
      '',
      'Send one more turn into a session that already ran. The session keeps its history and its',
      'system prompt; you only supply the new message. Headless only.',
      '',
      '  <harness>          claude | codex | opencode — the one that ran it.',
      '  <session-id|last>  id from `cast sessions`, or the literal `last` for that folder\'s newest.',
      '  [launch-folder]    the folder the session ran in. Default: current directory.',
      '  -p TEXT | -f FILE  the message for this turn (required).',
      '  --dry-run          print the argv/cwd it would spawn as JSON, launch nothing.',
      '',
      '  --headed and -s/-S are refused: the session is already open and already has its prompt.',
      '',
      'example: cast resume claude last -p "now say it in Portuguese"',
    ],
    sessions: [
      `usage: ${SESSIONS_USAGE}`,
      '',
      'What ran in a folder — one line per session, newest first, across all three harnesses or',
      'just one. The ids printed here are what `cast resume` takes.',
      '',
      '  [harness]        claude | codex | opencode. Omitted = all three, merged.',
      '  [launch-folder]  which folder\'s sessions. Default: current directory.',
      '  -n N             keep at most N per harness (default 10), so one busy harness cannot',
      '                   crowd the others out of the merged view.',
      '  --json           machine-readable rows: harness, id, started (ISO), label.',
      '',
      'columns: harness, session id, started, first-prompt label.',
      '',
      'example: cast sessions claude .rbtv/goals/my-goal/seats/writer -n 3',
    ],
    monitor: [
      `usage: ${MONITOR_USAGE}`,
      '',
      'The freeze tripwire. Reports jobs that are ALIVE BUT FROZEN, and on --watch a job',
      'that left the roster (ENDED). Killing a stall is the caller\'s call. Two channels:',
      'harness progress, and a witness of life from the process tree + stdout capture.',
      'A freeze verdict needs BOTH silent. States:',
      '  STALLED         no harness progress for --stall seconds AND the tree shows no life.',
      '  NO-SIGNAL       no signal AND no work of any kind ever, --grace seconds past launch.',
      '  SUSPECT         harness silent but the tree is alive — never an event; verify first.',
      '  provider-limit  usage-limit / 429 / insufficient-balance in stdout or harness log.',
      '  DEADLINE        wall-clock --deadline exceeded, independent of activity.',
      '  ENDED           --watch: a seen-alive job is gone. Once, then suppressed.',
      '             ENDED <pid> <harness> <folder> alive=<N>s last-state=<state>',
      '',
      '  (no flags)         one-shot roster: FOLDER HARNESS MODEL PID ELAPSED PROGRESS STATE.',
      '  --watch            silent while healthy. Freeze → exit 3. Only ENDED → exit 4.',
      '                     Both in one poll → 3. Armed empty → 0. 4 is never 3: 3 is',
      '                     kill-or-verify authority; the departed process is already gone.',
      '                     Every event burst trails an ADVISORY line: this monitor is never',
      '                     authority to kill — verify life yourself first (owner, 2026-08-22).',
      '  --stall SECONDS    freeze threshold, default 600. Measured 0 false positives at 600',
      '                     across 12,371 healthy gaps / 94 runs — do not lower it. Nothing',
      '                     advances during a single long tool call.',
      '  --grace SECONDS    how long a fresh job may show no signal at all, default 60.',
      '  --poll SECONDS     --watch sleep between sweeps, default 30.',
      '  --deadline SECONDS wall-clock cap per job, default 14400 (4h). Independent of',
      '                     activity. Launch spawnSync uses the same cap (CAST_DEADLINE_MS).',
      '                     Monitor never kills — DEADLINE is advisory, like STALL.',
      '  --folder PREFIX    only jobs whose folder starts with PREFIX.',
      '  --json             roster as JSON. Refused with --watch (that form prints events).',
      '',
      'An empty roster means "no REGISTERED launch is live" — jobs started outside cast, or',
      'before the registry existed, are invisible here. It is not proof the box is quiet.',
      '',
      'example: cast monitor --watch --folder .rbtv/goals/my-goal',
    ],
    route: [
      `usage: ${ROUTE_USAGE}`,
      ...ROUTE_FORMS.map((f) => `       ${f}`),
      '',
      'Route answers ONE question: which worker runs this job. You answer four about the job.',
      'Deterministic — no network, no clock, no randomness: the same answers against the same',
      'catalog always give the same verdict. One JSON verdict on stdout, exit 1 on error.',
      'Three flags are REQUIRED (--access, --type, --class). There are no silent defaults: an',
      'unanswered question is a guess, and a guess is what this command exists to remove. The',
      'one RULED default is --optimize (owner 2026-08-22): omit it and you get PRICE, for',
      'every class alike. The class\'s levels are all that stands between a job and the',
      'cheapest model on the roster.',
      '',
      'THE INTERVIEW',
      '',
      '  --access open | bounded',
      '    Q: must the agent navigate and DISCOVER files on disk?',
      '       open     yes — it will roam a repo it was not handed. API workers are dropped:',
      '                an API worker has no disk.',
      '       bounded  no — known files only, or no disk at all. API workers stay in play.',
      '',
      '  --type code | text',
      '    Q: is the work code, or is it prose/analysis?',
      '       code     ranks on the coding score.',
      '       text     ranks on the reasoning score. PLANNING IS TEXT, even for a coding job —',
      '                deciding what to build is not writing it.',
      '',
      '  --class planner | broad | bounded | mechanical',
      '    Q: how bounded is the work? This picks BOTH the quality tiers in play and the effort.',
      '       planner     unbounded judgement, decides what others do.  tiers SOTA+L1  effort 3*',
      '       broad       wide but the goal is clear.                   tier  L1        effort 2/3',
      '       bounded     a defined change with a known shape.          tiers L1+L2     effort 2',
      '       mechanical  one obviously-correct edit, no judgement.     tiers L2+L3     effort 1',
      '    (effort shown as code/text where they differ. * planner\'s 3 is a FLOOR — the verdict',
      '     says effort_is_floor:true and YOU raise it for criticality, complexity or blast',
      '     radius. Route does not decide that.)',
      '    A class never unlocks a tier it blocks: --optimize quality on --class bounded picks',
      '    the best L1, never SOTA. Only planner reaches SOTA.',
      '',
      '  --optimize price | quality   (optional — omitted means price)',
      '    Q: cheapest worker that qualifies, or best worker that qualifies?',
      '       price    lowest $/M output tokens. Ties: higher score, then alphabetical.',
      '                A row with a blank cost sits OUT of price picks — unknown is not cheap.',
      '       quality  highest tier the class allows. Ties: higher score, then lower cost, then',
      '                alphabetical.',
      '       (omitted) PRICE — identical to passing --optimize price, for every class (owner',
      '                ruling 2026-08-22, replacing the two-band rule of the day before). A',
      '                class spanning two tiers now takes the cheaper row wherever it sits:',
      '                bounded (L1+L2) can answer with an L2. Only --optimize quality ranks',
      '                on tier and score at all.',
      '',
      '  --caps image   (optional)',
      '    Q: does the job need a specific capability?',
      '       image  SHORT-CIRCUITS everything: you get the image-generation row and none of the',
      '              other questions are asked. `cast route --caps image` on its own is valid.',
      '',
      'VERDICT',
      '  {"verdict":"route","harness":"claude","model":"opus-5","mode":"cli","effort":3,',
      '   "effort_is_floor":true,"alternates":[{"harness":...},{...}]}',
      '  mode is cli (launch it with `cast <harness> <model> <effort>`) or api (`cast api`).',
      '  The top-level worker IS the choice — launch it. `alternates` is the next two of the same',
      '  ranking, as backups for when the first cannot be launched; they share the same effort.',
      '  Fewer than two alternates (or none) just means the ranking was that short.',
      '  errors: {"error":"malformed_request"|"zero_candidates"|"no_models","details":...}',
      '',
      'BATCH — a whole team in one call',
      '  cast route --batch seats.json   (or --batch - to read the JSON from stdin)',
      '  Planning mode designs every seat at once; batch turns that into ONE deterministic',
      '  assignment table instead of N shell calls. Input is a JSON array of seat objects (or',
      '  {"seats":[...]}), each one the interview as an object with a unique name:',
      '    {"name":"planner","access":"open","type":"text","class":"planner",',
      '     "optimize":"quality"}',
      '  Same vocabulary and required-ness as the flags (optimize optional, same price default;',
      '  caps:["image"] short-circuits the same',
      '  way — and an unknown key on a seat is a refusal, never a silent ignore. Output, one',
      '  entry per seat in INPUT order, the name mapping each verdict back to its seat:',
      '    {"verdict":"route-batch","seats":[',
      '      {"name":"planner","verdict":"route","harness":...,"alternates":[...]},',
      '      {"name":"fixer","error":"zero_candidates","details":"..."}]}',
      '  Exit 0 only when EVERY seat routed; 1 when any seat errored. A per-seat error never',
      '  aborts the batch — every seat\'s problem is reported in its own entry, so the whole',
      '  plan is fixed in one pass. A bad envelope (unreadable file, invalid JSON, empty stdin,',
      '  empty or duplicate-named seat list) refuses the whole call with one',
      '  {"error":"malformed_request","details":[...]} object and routes nothing.',
      '  --explain attaches each seat\'s own trace to that seat\'s entry. --batch combines with',
      '  none of the interview flags, --caps or --catalog.',
      '',
      'THE CATALOG',
      '  Routing axes live in the shared table ignite/supervisor/models.csv (mode, harness, model, efforts,',
      '  image, level, reasoning, coding, cost, use, quality-override, price-override).',
      '  Launch mechanics stay in catalog.js and the',
      '  two are joined on harness+model — a CSV row with no catalog twin is excluded with a',
      '  warning, because route must never name something cast cannot launch.',
      '  Per-vault override, WHOLE-FILE replace (present = it IS the catalog):',
      '    {vault}/.rbtv/config/modules/core/sub-agents/models.csv',
      '',
      '  use — WHO may see a row (blank reads as route, so an older CSV behaves as it did):',
      '    route  the normal state: the row competes for verdicts.',
      '    panel  no verdict may name it; it stays in --catalog, which is where a panel picks its',
      '           seats. For a model worth a second opinion but never worth being the one answer.',
      '    off    routing ignores it entirely. Still launchable by hand, still listed by --catalog.',
      '  quality-override / price-override — Y means: inside ITS OWN LEVEL, this row wins that',
      '  ranking whatever the numbers say. It never crosses a level (an L2 quality-override still',
      '  loses to every eligible L1) and never bypasses a filter — availability, --access, --caps',
      '  and the class levels all run first, so an override only reorders survivors. Under the',
      '  default — which is a price ranking — price-override fires and quality-override does',
      '  not; making a quality-override bite takes an explicit --optimize quality.',
      '',
      'flags',
      '  --explain   attach the full trace: every row that dropped, at which stage, and why.',
      '  --catalog   print the roster INSTEAD of routing — every CSV row with its axes, whether',
      '              it is launchable, and whether its credential resolves. Asks nothing.',
      '              Add --json for the same rows as JSON.',
      '',
      'examples',
      '  cast route --access bounded --type code --class mechanical            # default = price',
      '  cast route --access bounded --type code --class mechanical --optimize price',
      '  cast route --access open --type text --class planner --optimize quality --explain',
      '  cast route --access bounded --type text --class broad --optimize price',
      '  cast route --caps image',
      '  cast route --batch seats.json --explain',
      '  cast route --catalog',
    ],
    api: [
      `usage: ${API_USAGE}`,
      '',
      'Run one API worker (no CLI harness involved) and write its output to disk. GOOGLE ONLY:',
      'the Gemini chat worker and the Google image-generation worker. `cast route --catalog`',
      'shows which rows have mode=api.',
      '',
      '  <model>                which api row to call (see `cast route --catalog`).',
      '  <effort 1-5>           mapped onto that model\'s own reasoning ladder. 1 = thinking off.',
      '  -p TEXT                the prompt, typed inline. Saved to <output-folder>/prompt.md.',
      '  -f FILE                the prompt, read from a file. Mutually exclusive with -p.',
      '  --output-folder DIR    where the response and run artifacts are written. Required.',
      '  --image                image generation: prompt in, image FILES out into the output',
      '                         folder. No JSON envelope is asked for and none is parsed.',
      '  --target-file PATH     append this file\'s contents to the prompt.',
      '  --timeout N            seconds to wait before giving up.',
      '  --grounded             enable Google web-grounding. Refused together with --image.',
      '  --extra-params JSON    raw provider parameters merged into the request body.',
      '  --dry-run              print the request it would send, call nothing, write nothing.',
      '',
      'example: cast api gemini-3.5-flash 3 -p "summarise this" --output-folder out/',
      '         cast api gemini-3.5-flash 1 --image -p "a red bicycle" --output-folder out/',
    ],
    doctor: [
      'usage: cast doctor [--json]',
      '',
      'Is the machine able to cast? Shows which harnesses and providers are installed and',
      'authenticated, plus current usage. Delegates to `acct` (which owns that inventory), so',
      '`acct` must be on PATH.',
      '',
      '  --json  both sections as one JSON object instead of the text report.',
      '',
      'example: cast doctor',
    ],
    list: [
      'usage: cast list [--json]',
      '',
      'The model inventory: every harness/model cast can launch and what each effort number 1-5',
      'means on that model\'s ladder. Same table as the middle of `cast -h`, without the rest.',
      '',
      '  --json  {harness: {model: [rung, ...]}} — an empty array means the model has no effort',
      '          dial, so any number is accepted and no flag is emitted.',
      '',
      'example: cast list --json',
    ],
  };
}

module.exports = {
  printHelp, verbHelpPages,
};
