#!/usr/bin/env python3
"""reply_comment.py — reply inside an existing hypresent comment thread and/or
set/clear its agent-instruction flag.

The agent supplies the target thread id and the action(s). This tool drives the
REAL hypresent runtime headlessly to:
  1. open the deck in the app,
  2. locate the existing thread by id,
  3. append a reply through the runtime command bus (when --reply is given),
  4. set or clear the thread's agentInstruction flag through the runtime command
     bus (when --set-agent or --clear-agent is given),
  5. save through the app's own save handler.

The #hyp-comments island, the element data-hyp-agent stamp, and the
agent-instruction head block are regenerated by the runtime on save — they are
never hand-edited.

Usage:
  python tools/reply_comment.py --file deck.html --comment-id <id>
      [--reply "<text>"] [--author "<name>"] [--set-agent | --clear-agent] [--out new.html]

Exit 0 on success (prints a JSON summary). Non-zero with a clear message on any
failure (thread not found, command not confirmed, save failed).
"""
import argparse
import json
import os
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, ".."))   # hypresent/


# --- minimal app-driving helpers (kept self-contained; mirror tests/e2e) ---

def _free_port():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def _start_server(port):
    env = dict(os.environ)
    env["HYP_TEST_DIALOG"] = "1"   # enables the fake-dialog seam used to open/save by path
    proc = subprocess.Popen(
        [sys.executable, "server/server.py", "127.0.0.1", str(port)],
        cwd=REPO, env=env,
    )
    base = f"http://127.0.0.1:{port}"
    deadline = time.time() + 8
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(base + "/app/", timeout=1):
                return proc, base
        except Exception:
            time.sleep(0.1)
    proc.terminate()
    raise RuntimeError(f"hypresent server did not start on {port}")


def _post_json(base, path, payload):
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        base + path, data=data,
        headers={"Content-Type": "application/json"}, method="POST",
    )
    with urllib.request.urlopen(req, timeout=15) as r:
        return r.status, json.loads(r.read().decode("utf-8"))


def _set_fake_dialog(base, path_or_none):
    return _post_json(base, "/api/_test/set-dialog", {"path": path_or_none})


def _doc_eval(page, body):
    """Run a JS function body (receiving doc, win) against the deck iframe."""
    return page.evaluate(
        """(body) => {
            const f = document.querySelector('iframe.doc-frame');
            const doc = f.contentDocument, win = f.contentWindow;
            const fn = new Function('doc','win', body);
            return fn(doc, win);
        }""",
        body,
    )


def _fail(msg, code=2):
    print(f"reply_comment: ERROR — {msg}", file=sys.stderr)
    sys.exit(code)


def _find_thread(comments, comment_id):
    for t in comments:
        if t.get("id") == comment_id:
            return t
    return None


def _read_comments(page):
    return _doc_eval(page, "return win.hyp.comments.toJson();")


def _wait_and_confirm(page, predicate, tries=2, delay_ms=400):
    """Wait briefly and re-read comments until predicate holds or we run out of tries."""
    for _ in range(tries):
        page.wait_for_timeout(delay_ms)
        comments = _read_comments(page)
        if predicate(comments):
            return comments
    return None


def _post_command(page, command_type, payload):
    page.evaluate(
        """(args) => {
            const f = document.querySelector('iframe.doc-frame');
            f.contentWindow.postMessage(
                { source: 'hyp', kind: 'command', type: args.type, payload: args.payload, id: 'tool-' + args.type },
                location.origin);
        }""",
        {"type": command_type, "payload": payload},
    )


def main():
    ap = argparse.ArgumentParser(description="Reply to an existing hypresent comment thread and/or toggle its agent flag.")
    ap.add_argument("--file", required=True, help="Path to the HTML deck.")
    ap.add_argument("--comment-id", required=True, help="Existing comment thread id.")
    ap.add_argument("--reply", default=None, help="Reply body text to append to the thread.")
    ap.add_argument("--author", default="Agent", help="Author identity for the reply.")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--set-agent", action="store_true", help="Tag the thread as an agent instruction.")
    g.add_argument("--clear-agent", action="store_true", help="Remove the agent-instruction tag from the thread.")
    ap.add_argument("--out", default=None, help="Optional output path. Default: save in place (overwrites --file).")
    args = ap.parse_args()

    if not args.reply and not args.set_agent and not args.clear_agent:
        _fail("at least one action is required: --reply, --set-agent, or --clear-agent")

    src = os.path.abspath(args.file)
    if not os.path.isfile(src):
        _fail(f"file not found: {src}")
    out = os.path.abspath(args.out) if args.out else src

    # Conforming-deck precheck (the server rejects non-<section> HTML on load).
    with open(src, encoding="utf-8") as f:
        if "<section" not in f.read():
            _fail("not a conforming hypresent deck — no <section> slides found. "
                  "Hypresent only opens decks built from <section> blocks.")

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        _fail("playwright is not installed in this environment.", code=3)

    proc, base = _start_server(_free_port())
    pw = browser = None
    try:
        pw = sync_playwright().start()
        browser = pw.chromium.launch(headless=True)
        page = browser.new_page()
        # Seed the author so the runtime never prompts.
        page.add_init_script(
            "window.localStorage.setItem('hypresent-comment-author', %s);" % json.dumps(args.author)
        )
        page.goto(base + "/app/")

        # Open the deck by path via the fake-dialog seam, wait for the runtime.
        _set_fake_dialog(base, src)
        page.click("#open-btn")
        page.wait_for_function(
            """() => { const f = document.querySelector('iframe.doc-frame');
                       return f && f.contentWindow && f.contentWindow.hyp; }""",
            timeout=20000,
        )

        # Read the existing thread state.
        comments = _read_comments(page)
        thread_before = _find_thread(comments, args.comment_id)
        if thread_before is None:
            _fail(f"no comment thread with id {args.comment_id!r} in the deck")

        thread_count_before = len(comments)
        replies_before = len(thread_before.get("replies") or [])
        resolved_before = bool(thread_before.get("resolved"))
        agent_before = bool(thread_before.get("agentInstruction"))

        reply_added = False
        reply_author_out = None
        reply_body_out = None
        agent_instruction_out = agent_before

        if args.reply:
            if not args.reply.strip():
                _fail("--reply body must be non-empty")
            _post_command(page, "reply-comment", {
                "commentId": args.comment_id,
                "body": args.reply,
                "author": args.author,
            })

            def _reply_confirmed(c):
                t = _find_thread(c, args.comment_id)
                if t is None:
                    return False
                if len(c) != thread_count_before:
                    return False
                reps = t.get("replies") or []
                if len(reps) != replies_before + 1:
                    return False
                last = reps[-1]
                return (last.get("author") == args.author and
                        last.get("body") == args.reply and
                        bool(t.get("resolved")) == resolved_before)

            comments = _wait_and_confirm(page, _reply_confirmed)
            if comments is None:
                _fail(f"reply-comment command was not confirmed for thread {args.comment_id!r}")

            thread_after = _find_thread(comments, args.comment_id)
            last_reply = thread_after.get("replies")[-1]
            reply_added = True
            reply_author_out = last_reply.get("author")
            reply_body_out = last_reply.get("body")
            agent_instruction_out = bool(thread_after.get("agentInstruction"))

        if args.set_agent or args.clear_agent:
            want_agent = bool(args.set_agent)
            _post_command(page, "tag-agent", {
                "commentId": args.comment_id,
                "agentInstruction": want_agent,
            })

            def _tag_confirmed(c):
                t = _find_thread(c, args.comment_id)
                return t is not None and bool(t.get("agentInstruction")) == want_agent

            comments = _wait_and_confirm(page, _tag_confirmed)
            if comments is None:
                _fail(f"tag-agent command was not confirmed for thread {args.comment_id!r}")

            thread_after = _find_thread(comments, args.comment_id)
            agent_instruction_out = bool(thread_after.get("agentInstruction"))

        # Save through the app's own handler.
        if out != src:
            _set_fake_dialog(base, out)
            page.click("#save-as-btn")
        else:
            page.click("#save-btn")
        page.wait_for_function(
            "() => document.getElementById('doc-state')?.textContent === 'Saved'",
            timeout=8000,
        )

        # Confirm the saved file carries the island.
        with open(out, encoding="utf-8") as f:
            saved = f.read()
        if 'id="hyp-comments"' not in saved:
            _fail("save completed but the saved file has no #hyp-comments island.")

        thread_final = _find_thread(comments, args.comment_id)
        print(json.dumps({
            "ok": True,
            "file": out,
            "comment_id": args.comment_id,
            "reply_added": reply_added,
            "reply_author": reply_author_out,
            "reply_body": reply_body_out,
            "agent_instruction": agent_instruction_out,
            "replies_count": len(thread_final.get("replies") or []) if thread_final else None,
            "thread_count": len(comments),
        }, indent=2))
    finally:
        if browser:
            browser.close()
        if pw:
            pw.stop()
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except Exception:
            proc.kill()


if __name__ == "__main__":
    main()
