"""Every literal the installer is built from — names, paths, banners, the
harness set and the exposure-adapter matrix.
"""
from __future__ import annotations

import os
from pathlib import Path


VERSION = "0.2.1"
# The program name is used in generated guidance banners. It is deliberately
# not part of the portable install record.
INSTALLER_NAME = "install.py"
SCHEMA = 9

# D12 — ownership is a marker in the file, never a prefix on its name.
MANAGED_MARK = "rbtv-managed"

# The marker the 0.2 installer wrote. Still recognised as ours, so a migrated
# installation cleans up and replaces the files it wrote.
LEGACY_MARKS = ("rbtv2-managed",)

TOML_BANNER = (f"# {MANAGED_MARK} — generated by the rbtv installer; "
               "edits are overwritten on the next run\n")

# The harnesses that take hooks in a settings file; OpenCode's are JS plugins.
HOOK_HARNESSES = ("claude", "codex")

# Codex reads at most this many bytes of AGENTS.md files (its default is 32 KiB),
# joined from the git root down to the working folder: a guidance mirror plus
# component sections, with nested mirrors, can pass that. Written at the top of
# the installation's .codex/config.toml (read only in a trusted folder); cast
# passes the same value on every Codex launch.
CODEX_PROJECT_DOC_MAX_BYTES = 131072

MANAGED_BANNER = (f"<!-- {MANAGED_MARK} — generated by the rbtv installer; "
                  "edits are overwritten on the next run -->\n")

# The prefix runs before 2026-08-21 minted. Nothing writes it; the ownership
# test still recognizes it so the first unprefixed run cleans those files up.
LEGACY_PREFIX = "rbtv2-"

# The folder names, source files and whole-folder skills live in discovery.py.
# What a whole-folder skill's copy leaves behind.
SKILL_FOLDER_SKIP = frozenset({".git", "node_modules", "__pycache__"})

WS_PREFIX = "ws:"

STATE_REL = Path(".rbtv") / "config" / "install.json"
AGENT_RECORD = Path("agent.json")
PROMPT_FILE = Path("prompt.md")
# D14: the per-clone ignore file git reads beside .gitignore - never committed,
# so one machine's artifact list never overwrites another's.
EXCLUDE_REL = ".git/info/exclude"

# D1 — this file sits at `<repo>/core/rbtv/capabilities/tools/rbtv/lib/constants.py`, so the repo
# tree it scans is SIX directories up. Named once: every caller reads THIS,
# never `__file__`, because the difference between the two is a silently empty
# scan. `selftest/test_layout.py` fails the run if this stops being the repo.
REPO_ROOT = Path(__file__).resolve().parents[6]

INDEX_REL = Path(".rbtv") / "config" / "install-index.json"

# The supported providers: one file, kept beside cast's supported models and
# read by both programs. `core/rbtv/capabilities/providers.md` documents it.
PROVIDERS_FILE = (REPO_ROOT / "core" / "cast" / "capabilities" / "tools" / "cast"
                  / "providers.json")
# An installation's saved logins, one folder per provider.
PROVIDERS_REL = Path(".rbtv") / "config" / "rbtv" / "providers"
# The installation's environment file, where a provider's key variable may sit.
ENV_FILE_REL = Path(".rbtv") / "config" / "env" / ".env"

FENCE_ID = "rbtv"
# The fence the 0.2 installer wrote; read as ours, never written.
LEGACY_FENCE_ID = "rbtv2"

# POSIX shell syntax: .profile is also read by sh. Remove inherited copies so
# login and nested interactive shells keep the managed bin first, only once.
PATH_BOOTSTRAP = '''_rbtv_dir="$HOME/.rbtv/bin"
_rbtv_rest=":$PATH:"
while :; do
    case "$_rbtv_rest" in
        *":$_rbtv_dir:"*)
            _rbtv_before="${_rbtv_rest%%":$_rbtv_dir:"*}"
            _rbtv_after="${_rbtv_rest#*":$_rbtv_dir:"}"
            _rbtv_rest="$_rbtv_before:$_rbtv_after" ;;
        *) break ;;
    esac
done
_rbtv_rest="${_rbtv_rest#:}"
_rbtv_rest="${_rbtv_rest%:}"
PATH="$_rbtv_dir${_rbtv_rest:+:$_rbtv_rest}"
export PATH
unset _rbtv_dir _rbtv_rest _rbtv_before _rbtv_after'''

PATH_FENCE_START = f"# {FENCE_ID}:start path"

PATH_FENCE_END = f"# {FENCE_ID}:end path"

# The shell startup block the 0.2 installer wrote; replaced by the current one.
LEGACY_PATH_FENCE = (f"# {LEGACY_FENCE_ID}:start path",
                     f"# {LEGACY_FENCE_ID}:end path")

# Selftest rebinds these to a temp installation. Production: None → $HOME.
_RUNTIME: dict = {"bin": None, "rc": None, "local": None}

# D8/D13 — CMP-12's `agents.md` row: each harness's per-folder guidance
# FILENAME. The mirror is keyed by this map and nothing else: targets = the
# installed harnesses' filenames minus the basis. (CMP-12 also models qwen =
# QWEN.md; qwen is not one of D4's harnesses, so no run can select it and
# nothing is minted for it.)
GUIDANCE_FILE = {"claude": "CLAUDE.md", "codex": "AGENTS.md",
                 "opencode": "AGENTS.md"}

# The names this installer recognizes as guidance files — the accepted basis
# values, and the only filenames the mirror collision/adoption gates apply to.
GUIDANCE_NAMES = tuple(sorted(set(GUIDANCE_FILE.values())))

# Shared files are built from several types, rather than copied directly
# from one template.  Their destinations are named here so planning and
# an agent folder's fixed ignore file cannot diverge.
CODEX_CONFIG_FILE = ".codex/config.toml"
CLAUDE_MCP_FILE = ".mcp.json"
CLAUDE_SETTINGS_FILE = ".claude/settings.json"
OPENCODE_CONFIG_FILE = "opencode.json"
CODEX_HOOKS_FILE = ".codex/hooks.json"
SHARED_FILE_DESTINATIONS = (
    CODEX_CONFIG_FILE,
    CLAUDE_MCP_FILE,
    CLAUDE_SETTINGS_FILE,
    OPENCODE_CONFIG_FILE,
    CODEX_HOOKS_FILE,
)

# The section an agent folder's instructions file opens with. `agents.py`
# writes it; it is not a shared-file claim.
AGENT_SECTION_LABEL = "agent"

BASIS_NONE = "none"

# Directory names the recursive mirror walk never descends into.
GUIDANCE_SKIP_DIRS = frozenset({".git", "node_modules"})

# Prefixes excluded however the installation is configured: `.rbtv/goals` routers
# (BOTH names) are written by the goals-tree scaffold, in every installation.
GUIDANCE_ALWAYS_EXCLUDED = (".rbtv/goals",)

# A file whose head carries one of these is somebody's GENERATED mirror, not
# authored guidance — it can never be a basis (banner-over-banner).
GENERATED_MARKERS = ("AUTO-GENERATED MIRROR", "GENERATED by install.py",
                     "GENERATED by the rbtv installer",
                     # pre-rename banner: files minted before 2026-08-23 still
                     # carry it, and adoption must keep recognizing them.
                     "GENERATED by install2.py")

HARNESSES = ("claude", "codex", "opencode")
# The scopes `update` takes, in the order its help lists them.
UPDATE_SCOPES = ("guidance", "scaffolding", "all")

# The exposure methods a component's folders give its files: skill, rule,
# command and agent are harness files (an agent added with `rbtv add` is written as a
# harness-native sub-agent); hook and mcp-server are translated into
# harness settings; tool is placed on PATH; folder-instructions become a marked
# section in the target folder's instructions file. A method outside this set
# refuses.
CANONICAL_METHODS = (
    "skill", "rule", "command", "agent", "hook", "mcp-server", "tool",
    "folder-instructions",
)

# What `list`, `search` and `show` take as --type: the exposure methods, and
# three views of the source catalog that are never installed by type. `add` and
# `remove` take the exposure methods only.
LISTING_TYPES = (*CANONICAL_METHODS, "pack", "module", "component")
# The two listing types whose rows are groups of files, each its own table.
GROUP_TYPES = ("module", "component")

# Methods realized as ONE file per part, per harness. Target templates are
# install-root-relative; `{name}` is the bare part-id (D12). None = this
# harness has no realization for this method — nothing is minted, nothing is
# guessed.
#
# Transcribed from `architecture/CMP-12-exposure-adapter-matrix.md` (the ONE
# form authority) plus the codex/opencode readings re-measured 2026-08-08/09
# that `materialize-seats.py` carries. Kimi has no column: it shared every
# path with a harness that remains (skill → claude's `.claude/skills/`,
# rule → codex's `.agents/behavior-rules/`, command and sub-agent were None),
# so dropping it deletes no file.
MATRIX: dict[str, dict[str, str | None]] = {
    "skill": {
        "claude": ".claude/skills/{name}/SKILL.md",
        # opencode natively reads `.claude/` (CMP-12, widest claude-compat) —
        # same file, deduped by path.
        "opencode": ".claude/skills/{name}/SKILL.md",
        "codex": ".agents/skills/{name}/SKILL.md",
    },
    "command": {
        "claude": ".claude/commands/{name}.md",
        "codex": ".codex/prompts/{name}.md",
        "opencode": ".opencode/commands/{name}.md",
    },
    "rule": {
        "claude": ".claude/rules/{name}.md",
        # OpenCode reads no rules folder: the same file, deduped by path, is
        # listed in opencode.json `instructions`.
        "opencode": ".claude/rules/{name}.md",
        # Codex reads no rules folder either: its rule is a skill, which
        # Codex lists and opens when the model selects it.
        "codex": ".agents/skills/{name}/SKILL.md",
    },
    # An agent added with `rbtv add`: the harness's own sub-agent file. It is written
    # only for the harnesses the agent's record holds a model and an effort for.
    "agent": {
        "claude": ".claude/agents/{name}.md",
        "opencode": ".opencode/agents/{name}.md",
        "codex": ".codex/agents/{name}.toml",
    },
}

# The setting each harness's own sub-agent file has for a model and for an
# effort. None = that file has no such setting: the value is recorded and not
# applied. Read 2026-10-04 from claude 2.1.289 (its agent frontmatter fields),
# opencode 1.17.18 (its documented agent frontmatter fields) and codex 0.159.3
# (`codex doctor` accepts both keys in an agent role file and refuses an
# unknown one).
SUB_AGENT_SETTINGS: dict[str, dict[str, str | None]] = {
    "claude": {"model": "model", "effort": "effort"},
    "opencode": {"model": "model", "effort": "variant"},
    "codex": {"model": "model", "effort": "model_reasoning_effort"},
}
# The effort word rbtv records for a model whose `cast models list` row has no effort word.
EFFORT_INERT = "inert"


ANSI = {"ok": "\033[32m", "part": "\033[33m", "warn": "\033[33m",
        "gone": "\033[31m", "fail": "\033[31m", "reset": "\033[0m"}
