"""Every literal the installer is built from — names, paths, banners, the
harness set and the exposure-adapter matrix.
"""
from __future__ import annotations

import os
from pathlib import Path


VERSION = "0.2.1"
# The installer's own filename, recorded in the book so a reader of
# install.json can tell which tool wrote it. Informational: nothing branches
# on it. Books written before the 2026-08-23 rename carry "install2.py" and
# are simply overwritten on the next write.
INSTALLER_NAME = "install.py"

SCHEMA = 3

# D12 — ownership is a marker in the file, never a prefix on its name.
MANAGED_MARK = "rbtv-managed"

# The marker the 0.2 installer wrote. Still recognised as ours, so a migrated
# installation cleans up and replaces the files it wrote.
LEGACY_MARKS = ("rbtv2-managed",)

MANAGED_BANNER = (f"<!-- {MANAGED_MARK} — generated by the rbtv installer; "
                  "edits are overwritten on the next run -->\n")

# The prefix runs before 2026-08-21 minted. Nothing writes it; the ownership
# test still recognizes it so the first unprefixed run cleans those files up.
LEGACY_PREFIX = "rbtv2-"

# The folder names, unit files and whole-folder skills live in discovery.py.
SKILL_FOLDER_SKIP = frozenset({".git", "node_modules", "__pycache__"})

STATE_REL = Path(".rbtv") / "config" / "install.json"
# D14: the per-clone ignore file git reads beside .gitignore - never committed,
# so one machine's artifact list never overwrites another's.
EXCLUDE_REL = ".git/info/exclude"

# D1 — this file sits at `<repo>/meta/installer/lib/constants.py`, so the repo
# tree it scans is THREE directories up. Named once: every caller reads THIS,
# never `__file__`, because the difference between the two is a silently empty
# scan. `selftest/test_layout.py` fails the run if this stops being the repo.
REPO_ROOT = Path(__file__).resolve().parents[3]

INDEX_REL = Path(".rbtv") / "config" / "install-index.json"

FENCE_ID = "rbtv"
# The fence the 0.2 installer wrote; read as ours, never written.
LEGACY_FENCE_ID = "rbtv2"

# POSIX shell syntax: .profile is also read by sh. Remove inherited copies so
# login and nested interactive shells keep the managed bin first, only once.
PATH_BOOTSTRAP = '''_rbtv_dir="$HOME/.rbtv/bin"
_rbtv_rest=":$PATH:"
while :; do
    case "$_rbtv_rest" in
        *":$_rbtv_dir:"*)
            _rbtv_before="${_rbtv_rest%%":$_rbtv_dir:"*}"
            _rbtv_after="${_rbtv_rest#*":$_rbtv_dir:"}"
            _rbtv_rest="$_rbtv_before:$_rbtv_after" ;;
        *) break ;;
    esac
done
_rbtv_rest="${_rbtv_rest#:}"
_rbtv_rest="${_rbtv_rest%:}"
PATH="$_rbtv_dir${_rbtv_rest:+:$_rbtv_rest}"
export PATH
unset _rbtv_dir _rbtv_rest _rbtv_before _rbtv_after'''

PATH_FENCE_START = f"# {FENCE_ID}:start path"

PATH_FENCE_END = f"# {FENCE_ID}:end path"

# The shell startup block the 0.2 installer wrote; replaced by the current one.
LEGACY_PATH_FENCE = (f"# {LEGACY_FENCE_ID}:start path",
                     f"# {LEGACY_FENCE_ID}:end path")

# Selftest rebinds these to a temp workspace. Production: None → $HOME.
_RUNTIME: dict = {"bin": None, "rc": None, "local": None}

# D8/D13 — CMP-12's `agents.md` row: each harness's per-folder guidance
# FILENAME. The mirror is keyed by this map and nothing else: targets = the
# installed harnesses' filenames minus the basis. (CMP-12 also models qwen =
# QWEN.md; qwen is not one of D4's harnesses, so no run can select it and
# nothing is minted for it.)
GUIDANCE_FILE = {"claude": "CLAUDE.md", "codex": "AGENTS.md",
                 "opencode": "AGENTS.md"}

# The names this installer recognizes as guidance files — the accepted basis
# values, and the only filenames the mirror collision/adoption gates apply to.
GUIDANCE_NAMES = tuple(sorted(set(GUIDANCE_FILE.values())))

# CMP-12 § Fallback mechanics — the harnesses that auto-inject no rule folder,
# so their guidance file must FORCE the rule read. Not claude (`.claude/rules/`
# auto-injects) and not opencode (reads `.claude/` natively). Qwen is on this
# list in CMP-12 and absent from D4's harnesses. Kimi left with the 2026-08-14
# harness retirement — its models ride opencode.
FORCED_READ_HARNESSES = ("codex",)

BASIS_NONE = "none"

# Directory names the recursive mirror walk never descends into.
GUIDANCE_SKIP_DIRS = frozenset({".git", "node_modules"})

# Prefixes excluded however the workspace is configured: `.rbtv/goals` routers
# (BOTH names) are written by the goals-tree scaffold, in every workspace.
GUIDANCE_ALWAYS_EXCLUDED = (".rbtv/goals",)

# A file whose head carries one of these is somebody's GENERATED mirror, not
# authored guidance — it can never be a basis (banner-over-banner).
GENERATED_MARKERS = ("AUTO-GENERATED MIRROR", "GENERATED by install.py",
                     "GENERATED by the rbtv installer",
                     # pre-rename banner: files minted before 2026-08-23 still
                     # carry it, and adoption must keep recognizing them.
                     "GENERATED by install2.py")

HARNESSES = ("claude", "codex", "opencode")

# The exposure methods a component's folders give its units: skill, rule,
# command and agent are harness files; hook and mcp-server are translated into
# harness settings; tool is placed on PATH; folder-instructions become a marked
# section in the target folder's instructions file. A method outside this set
# refuses.
CANONICAL_METHODS = (
    "skill", "rule", "command", "agent", "hook", "mcp-server", "tool",
    "folder-instructions",
)

# Methods realized as ONE file per part, per harness. Target templates are
# install-root-relative; `{name}` is the bare part-id (D12). None = this
# harness has no realization for this method — nothing is minted, nothing is
# guessed.
#
# Transcribed from `architecture/CMP-12-exposure-adapter-matrix.md` (the ONE
# form authority) plus the codex/opencode readings re-measured 2026-08-08/09
# that `materialize-seats.py` carries. Kimi has no column: it shared every
# path with a harness that remains (skill → claude's `.claude/skills/`,
# rule → codex's `.agents/behavior-rules/`, command and sub-agent were None),
# so dropping it deletes no file.
MATRIX: dict[str, dict[str, str | None]] = {
    "skill": {
        "claude": ".claude/skills/{name}/SKILL.md",
        # opencode natively reads `.claude/` (CMP-12, widest claude-compat) —
        # same file, deduped by path.
        "opencode": ".claude/skills/{name}/SKILL.md",
        "codex": ".agents/skills/{name}/SKILL.md",
    },
    "command": {
        "claude": ".claude/commands/{name}.md",
        "codex": ".codex/prompts/{name}.md",
        "opencode": ".opencode/commands/{name}.md",
    },
    "rule": {
        "claude": ".claude/rules/{name}.md",
        "codex": ".agents/behavior-rules/{name}.md",
        # CMP-12 gives opencode NO separate rule type — it reads `.claude/`
        # natively, so claude's own file IS its realization (same dedupe by path
        # as the `skill` row above). It therefore takes no forced read either.
        "opencode": ".claude/rules/{name}.md",
    },
    "agent": {
        "claude": ".claude/agents/{name}.md",
        "opencode": ".opencode/agents/{name}.md",
        "codex": None,
    },
}


ANSI = {"ok": "\033[32m", "part": "\033[33m", "warn": "\033[33m",
        "gone": "\033[31m", "fail": "\033[31m", "reset": "\033[0m"}
