"""Every literal the installer is built from — names, paths, banners, the
harness set and the exposure-adapter matrix.
"""
from __future__ import annotations

import os
from pathlib import Path


VERSION = "2.0.0-coexistence"
# The installer's own filename, recorded in the book so a reader of
# install.json can tell which tool wrote it. Informational: nothing branches
# on it. Books written before the 2026-08-23 rename carry "install2.py" and
# are simply overwritten on the next write.
INSTALLER_NAME = "install.py"

SCHEMA = 2

# D12 — ownership is a marker in the file, never a prefix on its name.
MANAGED_MARK = "rbtv2-managed"

MANAGED_BANNER = (f"<!-- {MANAGED_MARK} — generated by {INSTALLER_NAME}; "
                  "edits are overwritten on the next run -->\n")

# The prefix runs before 2026-08-21 minted. Nothing writes it; the ownership
# test still recognizes it so the first unprefixed run cleans those files up.
LEGACY_PREFIX = "rbtv2-"

# EXPOSURE_NAME / EXPOSURE_COLS / HUB_* live in discovery.py (one definition).
SKILL_FOLDER_SKIP = frozenset({".git", "node_modules", "__pycache__"})

STATE_REL = Path(".rbtv") / "config" / "install.json"

# D1 — this file sits at `<repo>/meta/installer/lib/constants.py`, so the repo
# tree it scans is THREE directories up. Named once: every caller reads THIS,
# never `__file__`, because the difference between the two is a silently empty
# scan. `selftest/test_layout.py` fails the run if this stops being the repo.
REPO_ROOT = Path(__file__).resolve().parents[3]

INDEX_REL = Path(".rbtv") / "config" / "install-index.json"

FENCE_ID = "rbtv2"

# The one line the shell profile gets: bash/zsh syntax on POSIX,
# PowerShell $PROFILE syntax on Windows (the fences' `#` comments both).
PATH_BOOTSTRAP = (r'$env:Path = "$HOME\.rbtv\bin;" + $env:Path'
                  if os.name == "nt" else
                  'export PATH="$HOME/.rbtv/bin:$PATH"')

PATH_FENCE_START = f"# {FENCE_ID}:start path"

PATH_FENCE_END = f"# {FENCE_ID}:end path"

WS_PREFIX = "ws:"

# Selftest rebinds these to a temp workspace. Production: None → $HOME.
_RUNTIME: dict = {"bin": None, "rc": None, "local": None}

# D8/D13 — CMP-12's `agents.md` row: each harness's per-folder guidance
# FILENAME. The mirror is keyed by this map and nothing else: targets = the
# installed harnesses' filenames minus the basis. (CMP-12 also models qwen =
# QWEN.md; qwen is not one of D4's harnesses, so no run can select it and
# nothing is minted for it.)
GUIDANCE_FILE = {"claude": "CLAUDE.md", "codex": "AGENTS.md",
                 "opencode": "AGENTS.md"}

# The names this installer recognizes as guidance files — the accepted basis
# values, and the only filenames the mirror collision/adoption gates apply to.
GUIDANCE_NAMES = tuple(sorted(set(GUIDANCE_FILE.values())))

# CMP-12 § Fallback mechanics — the harnesses that auto-inject no rule folder,
# so their guidance file must FORCE the rule read. Not claude (`.claude/rules/`
# auto-injects) and not opencode (reads `.claude/` natively). Qwen is on this
# list in CMP-12 and absent from D4's harnesses. Kimi left with the 2026-08-14
# harness retirement — its models ride opencode.
FORCED_READ_HARNESSES = ("codex",)

BASIS_NONE = "none"

# Directory names the recursive mirror walk never descends into.
GUIDANCE_SKIP_DIRS = frozenset({".git", "node_modules"})

# Prefixes excluded however the workspace is configured: `.rbtv/goals` routers
# (BOTH names) are written by the goals-tree scaffold, in every workspace.
GUIDANCE_ALWAYS_EXCLUDED = (".rbtv/goals",)

# A file whose head carries one of these is somebody's GENERATED mirror, not
# authored guidance — it can never be a basis (banner-over-banner).
GENERATED_MARKERS = ("AUTO-GENERATED MIRROR", "GENERATED by install.py",
                     # pre-rename banner: files minted before 2026-08-23 still
                     # carry it, and adoption must keep recognizing them.
                     "GENERATED by install2.py")

HARNESSES = ("claude", "codex", "opencode")

# The canonical exposure-method vocabulary — d-exposure-method-canon (7) plus
# `path` (d-tool-inventory-exposure-rows) and `pool` (D22 — a prompt/task pool
# member, shopped at runtime by a seat, never minted as a harness artifact;
# registry transcription into d-exposure-method-canon rides F-113).
# A method outside this set refuses.
CANONICAL_METHODS = (
    "skill", "command", "rule", "hook", "sub-agent", "agents.md", "config",
    "path", "pool",
)

# Methods realized as ONE file per part, per harness. Target templates are
# install-root-relative; `{name}` is the bare part-id (D12). None = this
# harness has no realization for this method — nothing is minted, nothing is
# guessed.
#
# Transcribed from `architecture/CMP-12-exposure-adapter-matrix.md` (the ONE
# form authority) plus the codex/opencode readings re-measured 2026-08-08/09
# that `materialize-seats.py` carries. Kimi has no column: it shared every
# path with a harness that remains (skill → claude's `.claude/skills/`,
# rule → codex's `.agents/behavior-rules/`, command and sub-agent were None),
# so dropping it deletes no file.
MATRIX: dict[str, dict[str, str | None]] = {
    "skill": {
        "claude": ".claude/skills/{name}/SKILL.md",
        # opencode natively reads `.claude/` (CMP-12, widest claude-compat) —
        # same file, deduped by path.
        "opencode": ".claude/skills/{name}/SKILL.md",
        "codex": ".agents/skills/{name}/SKILL.md",
    },
    "command": {
        "claude": ".claude/commands/{name}.md",
        "codex": ".codex/prompts/{name}.md",
        "opencode": ".opencode/commands/{name}.md",
    },
    "rule": {
        "claude": ".claude/rules/{name}.md",
        "codex": ".agents/behavior-rules/{name}.md",
        # CMP-12 gives opencode NO separate rule type — it reads `.claude/`
        # natively, so claude's own file IS its realization (same dedupe by path
        # as the `skill` row above). It therefore takes no forced read either.
        "opencode": ".claude/rules/{name}.md",
    },
    "sub-agent": {
        "claude": ".claude/agents/{name}.md",
        "opencode": ".opencode/agents/{name}.md",
        "codex": None,
    },
}


INVENTORY_METHODS = ("pool",)

LOADER_NOTE = (
    f"Generated by {INSTALLER_NAME} from the component's exposure manifest "
    "(CMP-12 adapter matrix) — a thin loader, regenerated freely, never "
    "hand-edited."
)

ANSI = {"ok": "\033[32m", "part": "\033[33m", "warn": "\033[33m",
        "gone": "\033[31m", "fail": "\033[31m", "reset": "\033[0m"}
