"""Printing what a run planned or did, in the form a human reads."""
from __future__ import annotations

from . import present

_UPDATE_LABEL = {"guidance": "guidance", "scaffolding": "scaffolding",
                 "all": "all selected files"}


def _title(data: dict) -> str:
    """The `RBTV install — <outcome>` line — one authored place so
    configure/add/remove/update never spell their own title separately."""
    verb = data.get("_verb") or ""
    dry = bool(data.get("dry_run"))
    if verb == "configure":
        if data.get("changed") is False:
            return "configuration unchanged"
        return "configuration preview" if dry else "configuration saved"
    if verb == "add":
        return "add preview" if dry else "items added"
    if verb == "remove":
        if not data.get("uninstalled") and "report" in data:
            return "shared shortcut claims released"
        if not data.get("uninstalled") and not data.get("selected_items"):
            return "nothing removed"
        return "removal preview" if dry else "items removed"
    if verb == "update":
        label = _UPDATE_LABEL.get(data.get("scope", ""), data.get("scope", "update"))
        return f"{label} update preview" if dry else f"{label} updated"
    return "result"


def print_result(data: dict) -> None:
    print(present.title(_title(data)))
    print()
    if data.get("target"):
        print(f"Target: {data['target']} "
              f"({present.target_source_label(data.get('source'))})")
    if data.get("message"):
        print(data["message"])
    preview = bool(data.get("dry_run"))
    selected = data.get("selected_items") or []
    if selected:
        action = "Would remove" if data.get("uninstalled") else "Would install"
        if not preview:
            action = "Removed" if data.get("uninstalled") else "Installed"
        print(f"{action} items: {', '.join(selected)}")
    elif data.get("installed"):
        print(("Would refresh" if preview else "Refreshed")
              + " components: " + ", ".join(data["installed"]))
    elif data.get("uninstalled"):
        print(("Would remove" if preview else "Removed")
              + " components: " + ", ".join(data["uninstalled"]))
    if data.get("harnesses"):
        print(f"Receiving tools: {', '.join(data['harnesses'])}")
    # Printed BEFORE the dry-run branch: a planned takeover of another tool's
    # file is exactly what a human needs to see while deciding to proceed.
    # Tense MUST follow `preview` — a dry run adopts nothing; claiming
    # "now managed" before anything was written is a false completed-action
    # claim on a run that changed zero bytes.
    for rel in data.get("adopted") or []:
        print(f"  ^ {rel} (previously generated by a tool; "
              + ("would become managed here)" if preview else "now managed here)"))
    # A DIFFERENT thing from the whole-file adoption above: only the owned
    # section inside an already-existing file was taken over — the file
    # itself, and everything else in it, was never touched.
    for rel in data.get("adopted_sections") or []:
        print(f"  ^ {rel}: "
              + ("would adopt its existing owned section only " if preview
                 else "adopted its existing owned section only ")
              + "(the rest of the file is untouched)")
    for rel in data.get("released") or []:
        print(f"  ! {rel} (no longer managed here; kept on disk)")
    report = data.get("report") or {}
    if data.get("dry_run"):
        planned = data.get("planned_changes") or {}
        _print_changes(planned.get("write_files") or [],
                       planned.get("delete_files") or [],
                       planned.get("unchanged_files") or [],
                       planned.get("write_shared_files") or [],
                       planned.get("delete_shared_files") or [],
                       planned.get("unchanged_shared_files") or [],
                       tense="planned")
        for cid in data.get("shared_removed") or []:
            print(f"  ~- claim released: {cid}")
        _print_report_rows(report, planned=True)
        _print_gitignore(report, planned=True)
        _print_guidance(report, planned=True, scope=data.get("scope"))
        _print_guidance_sections(report, planned=True)
        print()
        print("Next: " + data.get("next", "rbtv install status"))
        return
    _print_changes(data.get("written") or [], data.get("deleted") or [],
                   data.get("skipped") or [],
                   data.get("shared_written") or [],
                   data.get("shared_deleted") or [],
                   data.get("shared_skipped") or [],
                   tense="applied")
    for cid in data.get("shared_removed") or []:
        print(f"  ~- claim released: {cid}")
    _print_report_rows(report, planned=False)
    _print_gitignore(report, planned=False)
    _print_guidance(report, planned=False, scope=data.get("scope"))
    _print_guidance_sections(report, planned=False)
    print()
    print("Next: " + data.get("next", "rbtv install status"))


def _print_changes(write_files: list[str], delete_files: list[str],
                   unchanged_files: list[str], write_shared: list[str],
                   delete_shared: list[str], unchanged_shared: list[str],
                   *, tense: str) -> None:
    """The file-change summary and its detail lines. ONE shape for both a
    preview (`apply()`'s `planned_changes`) and a real run's actual
    written/deleted/shared_* result — real counts, always, so a zero-change
    reinstall reads as zero rather than being inferred from an empty list
    that could just as easily mean 'not checked'. Shared-CLAIM ids (which
    `apply()` also returns, as `shared`/`shared_removed`) never enter this
    count — only real shared FILE paths do, because a claim id is not a
    file-change count."""
    write_v = "would write" if tense == "planned" else "wrote"
    delete_v = "would delete" if tense == "planned" else "deleted"
    lead = "Preview: " if tense == "planned" else "Result: "
    unchanged = len(unchanged_files) + len(unchanged_shared)
    print(f"{lead}{write_v} {len(write_files)} file(s), {delete_v} "
          f"{len(delete_files)} file(s); {write_v} {len(write_shared)} "
          f"shared file(s), {delete_v} {len(delete_shared)} shared file(s); "
          f"{unchanged} file(s) already match and stay untouched.")
    for rel in write_files:
        print(f"  + {rel}")
    for rel in delete_files:
        print(f"  - {rel}")
    for rel in write_shared:
        print(f"  ~ {rel}")
    for rel in delete_shared:
        print(f"  ~- {rel}")


def _print_report_rows(report: dict, planned: bool) -> None:
    """Why a manifest row minted nothing. Printed on DRY RUNS TOO, marked as
    planned (task 7.622): `install --component X --dry-run` is the command the
    acceptance sketches name, and suppressing these rows there left the human
    ~11 lines with no per-row detail while the data sat in `--json` all along.
    The two lists are the SAME data a real run prints; only the tense moves."""
    verb = "would skip" if planned else "skipped"
    tail = "no file would be written" if planned else "no file was written"
    for row in report.get("skipped_inventory_rows") or []:
        print(f"  · {verb} {row['component']}#{row['part']}: "
              "reference only; no file to install")
    for row in report.get("skill_folders") or []:
        print(f"  · {'would copy' if planned else 'copied'} skill folder "
              f"{row['component']} whole — {row['files']} file(s) into "
              + ", ".join(row["roots"]))
    for row in report.get("no_realization") or []:
        print(f"  · {row['harness']} cannot use this {row['type']} item "
              f"({row['component']}#{row['part']}) — {tail}")
    pathrep = report.get("path") or {}
    for name in pathrep.get("linked") or []:
        print(f"  · {'would link' if planned else 'linked'} PATH {name}")
    for name in pathrep.get("relinked") or []:
        print(f"  · {'would relink' if planned else 'relinked'} PATH {name}")
    for name in pathrep.get("unlinked") or []:
        print(f"  · {'would unlink' if planned else 'unlinked'} PATH {name}")
    for name in pathrep.get("kept_shared") or []:
        print(f"  · kept shared shortcut {name} for another workspace")
    for name in pathrep.get("legacy_preserved") or []:
        print(f"  · kept {name}: its earlier ownership is uncertain")
    setup = report.get("path_setup") or {}
    if planned and any(pathrep.get(k) for k in ("linked", "relinked", "ok")):
        print("  · applying this plan would attempt to put ~/.rbtv/bin "
              "on the user PATH")
    elif setup.get("attempted") and setup.get("ok"):
        print("  · ~/.rbtv/bin is on the user PATH")
    warning = report.get("path_warning")
    if warning:
        print("  · WARNING: component installation succeeded, but PATH "
              f"setup failed: {warning['message']}")
        print("    Recovery: " + warning["recovery"])


def _print_gitignore(report: dict, planned: bool) -> None:
    """What the `.git/info/exclude` block covers — and what it cannot (D14)."""
    gi = report.get("gitignore")
    if not gi:
        return
    if not gi.get("claimed"):
        print(f"  · git exclude: not claimed ({gi.get('reason')})")
        return
    print(f"  · Git ignore list {'would keep' if planned else 'keeps'} "
          f"{gi['count']} generated path(s) out of commits")
    for rel in gi.get("tracked") or []:
        print(f"    ⚠ {rel} is ALREADY TRACKED by git — no ignore rule reaches "
              "a tracked file. Untrack it (`git rm --cached`) or accept that "
              "it is committed.")


def _print_guidance(report: dict, planned: bool, *, scope: str | None = None) -> None:
    """The guidance-MIRROR summary only — the maintained HUMAN text this
    scope copies from the basis into each counterpart file. Owner-ruled
    content split: this copies text only, never generated sections. Whether
    a destination's OWN existing generated section survives untouched
    depends on `scope` — `_add_mirror` only skips rewriting it (preserves
    it as-is) when `scope == "guidance"`; `all`/`add` rebuild it via their
    own planned claims in the SAME run, so claiming it "is preserved" there
    would be false. `_print_guidance_sections` below reports that
    regeneration truthfully; this function makes no claim about it except
    the one case where preservation is actually guaranteed. Printed on dry
    runs too, with the tense moved to match."""
    verb = "would generate" if planned else "generated"
    mirror = report.get("guidance_mirror")
    if mirror and mirror.get("skipped"):
        print(f"  · guidance mirror: SKIPPED ({mirror['skipped']}) — the "
              "maintained-text copy step was skipped; fix the basis on the "
              "next install. This does not describe the rest of the run — "
              "other files this run planned may still be written.")
    elif mirror and mirror.get("basis") and not mirror.get("targets"):
        print(f"  · guidance mirror: nothing to copy — every installed "
              f"harness reads {mirror['basis']} directly, so there is no "
              "separate counterpart file to maintain.")
    elif mirror and mirror.get("basis"):
        print(f"  · guidance mirror: {mirror['count']} file(s) — "
              f"{', '.join(mirror['targets'])}: maintained text {verb} from "
              f"{mirror['basis']}; generated sections are not copied from "
              "the basis"
              + (f"; excluding {', '.join(mirror['excludes'])}"
                 if mirror.get("excludes") else ""))
        if scope == "guidance":
            print("    each destination's own existing generated "
                  "instruction section is preserved as-is by this copy")
        if mirror.get("banner_stripped"):
            print("    a generated banner was stripped from these bases before "
                  "mirroring (never stacked): "
                  + ", ".join(mirror["banner_stripped"]))
    elif mirror:
        print("  · guidance copies: off. To choose an authored file, run "
              "`rbtv install configure --guidance CLAUDE.md` or "
              "`--guidance AGENTS.md`.")
    if report.get("guidance_debannered"):
        print(f"  · {'would clean' if planned else 'cleaned'} a stale GENERATED "
              "banner off the file(s) you now author: "
              + ", ".join(report["guidance_debannered"]))
    # The old `guidance_manual` block asked a human to hand-paste a fenced
    # rule section into their guidance file. That is obsolete: `update
    # scaffolding`/`add` now writes owned instruction sections into every
    # configured file automatically, so there is nothing left to paste — see
    # mechanics' report data for the current field shape once it lands.


def _print_guidance_sections(report: dict, planned: bool) -> None:
    """`report.guidance_sections`: the root instruction files whose owned
    fenced section this run REGENERATES — mechanics' field means "rebuilt",
    never "merely present" or "left as-is"; a file whose section this run
    only preserved untouched does not belong in this list, and this printer
    never claims a file was regenerated on the strength of that list
    including it for some other reason. Never a manual paste instruction,
    and never the whole-file guidance-text copy (that is `_print_guidance`
    above; a `guidance_sections` entry is one GENERATED section INSIDE a
    file the human still authors the rest of, and scaffolding and guidance
    can both touch that same file for their own separate reasons)."""
    sections = report.get("guidance_sections") or []
    if not sections:
        return
    verb = "will regenerate" if planned else "regenerated"
    print(f"  · {verb} the automatically managed instruction section in: "
          + ", ".join(sections))
