"""Printing what a run planned or did, in the form a human reads."""
from __future__ import annotations


def print_result(data: dict) -> None:
    if data.get("target"):
        print(f"Target: {data['target']} (chosen by {data.get('source') or 'caller'}). "
              "Override with --target PATH.")
    if data.get("message"):
        print(data["message"])
    preview = bool(data.get("dry_run"))
    selected = data.get("selected_items") or []
    if selected:
        action = "Would remove" if data.get("uninstalled") else "Would install"
        if not preview:
            action = "Removed" if data.get("uninstalled") else "Installed"
        print(f"{action} items: {', '.join(selected)}")
    elif data.get("installed"):
        print(("Would refresh" if preview else "Refreshed")
              + " components: " + ", ".join(data["installed"]))
    elif data.get("uninstalled"):
        print(("Would remove" if preview else "Removed")
              + " components: " + ", ".join(data["uninstalled"]))
    if data.get("harnesses"):
        print(f"AI tools: {', '.join(data['harnesses'])}")
    # Printed BEFORE the dry-run branch: a planned takeover of another tool's
    # file is exactly what a human needs to see while deciding to proceed.
    for rel in data.get("adopted") or []:
        print(f"  ^ {rel} (previously generated by a tool; now managed here)")
    for rel in data.get("released") or []:
        print(f"  ! {rel} (no longer managed here; kept on disk)")
    if data.get("dry_run"):
        print(f"Preview: would write {len(data.get('skipped') or [])} file(s) "
              f"and update {len(data.get('shared') or [])} shared setting(s):")
        for rel in data.get("skipped") or []:
            print(f"  + {rel}")
        for rel in data.get("shared") or []:
            print(f"  ~ {rel}")
        for rel in data.get("deleted") or []:
            print(f"  - {rel}")
        for rel in data.get("shared_removed") or []:
            print(f"  ~- {rel}")
        _print_report_rows(data.get("report") or {}, planned=True)
        _print_gitignore(data.get("report") or {}, planned=True)
        _print_guidance(data.get("report") or {}, planned=True)
        print("next: " + data.get("next", "rbtv install status"))
        return
    for rel in data.get("written") or []:
        print(f"  + {rel}")
    for rel in data.get("skipped") or []:
        print(f"  = {rel} (unchanged)")
    for rel in data.get("shared") or []:
        print(f"  ~ {rel}")
    for rel in data.get("deleted") or []:
        print(f"  - {rel}")
    for rel in data.get("shared_removed") or []:
        print(f"  ~- {rel}")
    report = data.get("report") or {}
    _print_report_rows(report, planned=False)
    _print_gitignore(report, planned=False)
    _print_guidance(report, planned=False)
    print("next: " + data.get("next", "rbtv install status"))


def _print_report_rows(report: dict, planned: bool) -> None:
    """Why a manifest row minted nothing. Printed on DRY RUNS TOO, marked as
    planned (task 7.622): `install --component X --dry-run` is the command the
    acceptance sketches name, and suppressing these rows there left the human
    ~11 lines with no per-row detail while the data sat in `--json` all along.
    The two lists are the SAME data a real run prints; only the tense moves."""
    verb = "would skip" if planned else "skipped"
    tail = "no file would be written" if planned else "no file was written"
    for row in report.get("skipped_inventory_rows") or []:
        print(f"  · {verb} {row['component']}#{row['part']}: "
              "reference only; no file to install")
    for row in report.get("skill_folders") or []:
        print(f"  · {'would copy' if planned else 'copied'} skill folder "
              f"{row['component']} whole — {row['files']} file(s) into "
              + ", ".join(row["roots"]))
    for row in report.get("no_realization") or []:
        print(f"  · {row['harness']} cannot use this {row['method']} item "
              f"({row['component']}#{row['part']}) — {tail}")
    pathrep = report.get("path") or {}
    for name in pathrep.get("linked") or []:
        print(f"  · {'would link' if planned else 'linked'} PATH {name}")
    for name in pathrep.get("relinked") or []:
        print(f"  · {'would relink' if planned else 'relinked'} PATH {name}")
    for name in pathrep.get("unlinked") or []:
        print(f"  · {'would unlink' if planned else 'unlinked'} PATH {name}")
    for name in pathrep.get("kept_shared") or []:
        print(f"  · kept shared shortcut {name} for another workspace")
    for name in pathrep.get("legacy_preserved") or []:
        print(f"  · kept {name}: its earlier ownership is uncertain")
    setup = report.get("path_setup") or {}
    if planned and any(pathrep.get(k) for k in ("linked", "relinked", "ok")):
        print("  · applying this plan would attempt to put ~/.rbtv/bin "
              "on the user PATH")
    elif setup.get("attempted") and setup.get("ok"):
        print("  · ~/.rbtv/bin is on the user PATH")
    warning = report.get("path_warning")
    if warning:
        print("  · WARNING: component installation succeeded, but PATH "
              f"setup failed: {warning['message']}")
        print("    Recovery: " + warning["recovery"])


def _print_gitignore(report: dict, planned: bool) -> None:
    """What the `.git/info/exclude` block covers — and what it cannot (D14)."""
    gi = report.get("gitignore")
    if not gi:
        return
    if not gi.get("claimed"):
        print(f"  · git exclude: not claimed ({gi.get('reason')})")
        return
    print(f"  · Git ignore list {'would keep' if planned else 'keeps'} "
          f"{gi['count']} generated path(s) out of commits")
    for rel in gi.get("tracked") or []:
        print(f"    ⚠ {rel} is ALREADY TRACKED by git — no ignore rule reaches "
              "a tracked file. Untrack it (`git rm --cached`) or accept that "
              "it is committed.")


def _print_guidance(report: dict, planned: bool) -> None:
    """The guidance-mirror summary and the blocks the human must place. Printed
    on DRY RUNS TOO: the basis is never written, so this is the only channel
    that ever names what the human still has to do (7.622's bug class)."""
    verb = "would generate" if planned else "generated"
    mirror = report.get("guidance_mirror")
    if mirror and mirror.get("skipped"):
        print(f"  · guidance mirror: SKIPPED ({mirror['skipped']}) — not "
              "re-rendered; both root guidance files were left untouched. Fix "
              "the basis on the next install.")
    elif mirror and mirror.get("basis") and not mirror.get("targets"):
        print(f"  · guidance mirror: nothing to render — every installed "
              f"harness reads {mirror['basis']}, which is the basis and is "
              "never written (D13).")
    elif mirror and mirror.get("basis"):
        print(f"  · guidance mirror: {mirror['count']} file(s) — "
              f"{', '.join(mirror['targets'])} {verb} from "
              f"{mirror['basis']} (one set beside every {mirror['basis']} in "
              "the tree; no basis file is ever written)"
              + (f"; excluding {', '.join(mirror['excludes'])}"
                 if mirror.get("excludes") else ""))
        if mirror.get("banner_stripped"):
            print("    a generated banner was stripped from these bases before "
                  "mirroring (never stacked): "
                  + ", ".join(mirror["banner_stripped"]))
    elif mirror:
        print("  · guidance copies: off. To choose an authored file, run "
              "`rbtv install set --guidance CLAUDE.md` or "
              "`--guidance AGENTS.md`.")
    if report.get("guidance_debannered"):
        print(f"  · {'would clean' if planned else 'cleaned'} a stale GENERATED "
              "banner off the file(s) you now author: "
              + ", ".join(report["guidance_debannered"]))
    for name, block in (report.get("guidance_manual") or {}).items():
        print(f"\nAdd this block to {name} — an installed harness reads it and "
              "this installer never writes it (D8). Copy from the next line to "
              "the closing fence:\n")
        # Flush, never indented: four leading spaces make markdown swallow the
        # whole block as a code span when it is pasted into the guidance file.
        print(block.rstrip())
